# Generated by Django 5.2.6 on 2025-10-17 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_image_videoroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoRoom',
        ),
    ]
