# Generated by Django 5.2.6 on 2025-09-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
