# Generated by Django 5.2.6 on 2025-10-10 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_my_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='my_user',
        ),
    ]
