# Generated by Django 5.2.6 on 2025-10-18 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_report_options_alter_tasktable_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='FamilyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('father_contact', models.CharField(max_length=20)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_contact', models.CharField(max_length=20)),
                ('wife_name', models.CharField(max_length=100)),
                ('home_address', models.TextField()),
                ('total_siblings', models.PositiveIntegerField()),
                ('brothers', models.PositiveIntegerField()),
                ('sisters', models.PositiveIntegerField()),
                ('total_children', models.PositiveIntegerField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
