# Generated by Django 5.2.6 on 2025-10-09 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notice_assigned_by_notice_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
