# Generated by Django 5.2.6 on 2025-10-09 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_notice_assigned_by_remove_notice_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='location_verified',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='longitude',
        ),
    ]
