# Generated by Django 5.2.6 on 2025-10-10 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_my_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='achievement_crt',
        ),
        migrations.RemoveField(
            model_name='document',
            name='appointment_letter',
        ),
        migrations.RemoveField(
            model_name='document',
            name='bonafide_crt',
        ),
        migrations.RemoveField(
            model_name='document',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='document',
            name='masters',
        ),
        migrations.RemoveField(
            model_name='document',
            name='offer_letter',
        ),
        migrations.RemoveField(
            model_name='document',
            name='releaving_letter',
        ),
        migrations.RemoveField(
            model_name='document',
            name='resignation_letter',
        ),
    ]
