# Generated by Django 5.2.6 on 2025-09-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_employee_age_employee_current_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='twelfth',
            new_name='twelth',
        ),
    ]
