# Generated by Django 5.2.6 on 2025-10-18 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee_blood_group_familydetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('father_contact', models.CharField(max_length=20)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_contact', models.CharField(max_length=20)),
                ('wife_name', models.CharField(max_length=100)),
                ('home_address', models.TextField()),
                ('total_siblings', models.PositiveIntegerField()),
                ('brothers', models.PositiveIntegerField()),
                ('sisters', models.PositiveIntegerField()),
                ('total_children', models.PositiveIntegerField()),
                ('bank_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('pf_no', models.CharField(max_length=50)),
                ('pf_uan', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=20)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FamilyDetails',
        ),
    ]
