# Generated by Django 5.2.6 on 2025-10-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employeedetails_delete_familydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
