# Generated by Django 5.2.6 on 2025-10-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_document_achievement_crt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='achievement_crt',
            field=models.FileField(blank=True, null=True, upload_to='documents/achievement_certificates/'),
        ),
        migrations.AddField(
            model_name='document',
            name='appointment_letter',
            field=models.FileField(blank=True, null=True, upload_to='documents/appointment_letters/'),
        ),
        migrations.AddField(
            model_name='document',
            name='bonafide_crt',
            field=models.FileField(blank=True, null=True, upload_to='documents/bonafide_certificates/'),
        ),
        migrations.AddField(
            model_name='document',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to='documents/certificates/'),
        ),
        migrations.AddField(
            model_name='document',
            name='masters',
            field=models.FileField(blank=True, null=True, upload_to='documents/masters/'),
        ),
        migrations.AddField(
            model_name='document',
            name='offer_letter',
            field=models.FileField(blank=True, null=True, upload_to='documents/offer_letters/'),
        ),
        migrations.AddField(
            model_name='document',
            name='releaving_letter',
            field=models.FileField(blank=True, null=True, upload_to='documents/releaving_letters/'),
        ),
        migrations.AddField(
            model_name='document',
            name='resignation_letter',
            field=models.FileField(blank=True, null=True, upload_to='documents/resignation_letters/'),
        ),
    ]
