# Generated by Django 5.2.6 on 2025-10-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_document_achievement_crt_document_appointment_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='achievement_crt',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='appointment_letter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='award',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='bonafide_crt',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='certificates',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='degree',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='id_proof',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='marks_card',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='masters',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='offer_letter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='releaving_letter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='resignation_letter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='resume',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='tenth',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='twelth',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
