# Generated by Django 5.2.6 on 2025-10-18 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_award_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='date',
        ),
    ]
