# Generated by Django 5.2.6 on 2025-10-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_award_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleavedEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('empid', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('offboarded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Releaved Employee',
                'verbose_name_plural': 'Releaved Employees',
                'db_table': 'accounts_releavedemployees',
            },
        ),
    ]
