# Generated by Django 5.2.6 on 2025-10-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_releavedemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='releavedemployee',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
