# Generated by Django 5.2.6 on 2025-10-11 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to=settings.AUTH_USER_MODEL),
        ),
    ]
