# Generated by Django 5.2.6 on 2025-10-18 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_releavedemployee_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releavedemployee',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='releavedemployee',
            name='empid',
        ),
        migrations.RemoveField(
            model_name='releavedemployee',
            name='profile_picture',
        ),
    ]
