# Generated by Django 5.2.6 on 2025-10-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_releavedemployee_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=50)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AlterField(
            model_name='releavedemployee',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
