# Generated by Django 5.2.6 on 2025-10-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_holiday_alter_releavedemployee_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='weekday',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='month',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('date', 'country')},
        ),
    ]
