# Generated by Django 5.2.6 on 2025-10-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_ticket_delete_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='achievement_crt',
            new_name='achievement_certificate',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='bonafide_crt',
            new_name='bonafide_certificate',
        ),
    ]
