# Generated by Django 5.2.6 on 2025-10-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_holiday_weekday_alter_holiday_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
