# Generated by Django 5.2.6 on 2025-10-15 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_achievement_crt_document_achievement_certificate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='achievement_certificate',
            new_name='achievement_crt',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='bonafide_certificate',
            new_name='bonafide_crt',
        ),
    ]
