# Generated by Django 5.2.6 on 2025-10-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_career'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={},
        ),
    ]
