# Generated by Django 5.2.6 on 2025-10-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_career_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Career',
        ),
    ]
