# Generated by Django 5.2.6 on 2025-10-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_career'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='id',
        ),
        migrations.AlterField(
            model_name='career',
            name='email',
            field=models.EmailField(db_column='email_id', max_length=254, primary_key=True, serialize=False),
        ),
    ]
