# Generated by Django 5.2.6 on 2025-10-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_career_id_alter_career_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Career',
            new_name='AppliedJobs',
        ),
        migrations.AlterModelTable(
            name='appliedjobs',
            table='Applied_Jobs',
        ),
    ]
