# Generated by Django 5.2.6 on 2025-10-24 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_rename_career_appliedjobs_alter_appliedjobs_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appliedjobs',
            table='accounts_appliedjobs',
        ),
    ]
