# Generated by Django 5.2.6 on 2025-10-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_appliedjobs_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='hired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appliedjobs',
            name='report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
