# Generated by Django 5.2.6 on 2025-10-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_appliedjobs_hired_appliedjobs_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('full_description', models.TextField()),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Contract', 'Contract')], default='Full-time', max_length=20)),
                ('experience', models.CharField(max_length=50)),
                ('salary', models.CharField(blank=True, max_length=50, null=True)),
                ('apply_link', models.URLField(blank=True, max_length=500, null=True)),
                ('posted_date', models.DateField()),
                ('category', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_postings',
            },
        ),
    ]
