# Generated by Django 5.2.6 on 2025-10-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_jobposting'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobposting',
            table='accounts_job_postings',
        ),
    ]
