# Generated by Django 5.2.6 on 2025-10-24 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_jobposting_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='full_description',
        ),
    ]
