# Generated by Django 5.2.6 on 2025-10-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_jobposting_full_description'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobposting',
            table='accounts_careers',
        ),
    ]
