# Generated by Django 5.2.6 on 2025-10-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_jobposting_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjobs',
            name='resume',
            field=models.URLField(blank=True, null=True),
        ),
    ]
