# Generated by Django 5.2.6 on 2025-10-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_appliedjobs_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedjobs',
            old_name='full_name',
            new_name='fullname',
        ),
    ]
