# Generated by Django 5.2.6 on 2025-10-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_rename_full_name_appliedjobs_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='LOP',
            field=models.IntegerField(default=0, help_text='Loss of pay days (unpaid leave)'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='STD',
            field=models.IntegerField(default=0, help_text='Number of standard working days in the month'),
        ),
    ]
