# Generated by Django 5.2.6 on 2025-10-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_payroll_lop_payroll_std'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='benefits',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='requirements',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='responsibilities',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='skills',
            field=models.TextField(),
        ),
    ]
