# Generated by Django 5.2.6 on 2025-10-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_releavedemployee_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='releavedemployee',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='releavedemployee',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
