# Generated by Django 5.2.6 on 2025-10-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_releavedemployee_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releavedemployee',
            name='approved',
            field=models.TextField(blank=True, null=True),
        ),
    ]
