# Generated by Django 5.2.6 on 2025-10-26 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_releavedemployee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releavedemployee',
            name='email',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='releaved_employees', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
