# Generated by Django 5.2.6 on 2025-10-26 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_releavedemployee_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='releavedemployee',
            options={'ordering': ['-offboarded_at'], 'verbose_name': 'Releaved Employee', 'verbose_name_plural': 'Releaved Employees'},
        ),
    ]
