# Generated by Django 5.2.6 on 2025-10-26 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_releavedemployee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releavedemployee',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='releaved_employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
