# Generated by Django 5.2.6 on 2025-10-26 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_releavedemployee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releavedemployee',
            name='offboarded_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
