# Generated by Django 5.2.6 on 2025-10-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_alter_releavedemployee_offboarded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releavedemployee',
            name='brothers',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='releavedemployee',
            name='sisters',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='releavedemployee',
            name='total_children',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='releavedemployee',
            name='total_siblings',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
