# Generated by Django 5.2.6 on 2025-10-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_releavedemployee_brothers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releavedemployee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
