# Generated by Django 5.2.6 on 2025-10-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_releavedemployee_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releavedemployee',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='releavedemployee',
            name='emp_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
