# Generated by Django 5.2.6 on 2025-10-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_releavedemployee_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='location_verified',
        ),
        migrations.AddField(
            model_name='attendance',
            name='location_type',
            field=models.CharField(choices=[('office', 'Office'), ('work', 'Work From Home')], default='office', max_length=10),
        ),
    ]
