# Generated by Django 5.2.6 on 2025-10-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_remove_attendance_location_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='releavedemployee',
            name='reason_for_resignation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
