# Generated by Django 5.2.6 on 2025-11-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_releavedemployee_reason_for_resignation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='releavedemployee',
            old_name='approved',
            new_name='hr_approved',
        ),
        migrations.RenameField(
            model_name='releavedemployee',
            old_name='description',
            new_name='hr_description',
        ),
        migrations.AddField(
            model_name='releavedemployee',
            name='manager_approved',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='releavedemployee',
            name='manager_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
