# Generated by Django 5.2.6 on 2025-11-03 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_rename_approved_releavedemployee_hr_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleavedAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_type', models.CharField(choices=[('office', 'Office'), ('work', 'Work From Home')], default='office', max_length=10)),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('releaved_employee_id', models.IntegerField(blank=True, help_text='Reference to ReleavedEmployee record', null=True)),
            ],
            options={
                'verbose_name': 'Releaved Attendance',
                'verbose_name_plural': 'Releaved Attendances',
                'db_table': 'accounts_releavedattendance',
                'ordering': ['-date', '-archived_at'],
            },
        ),
    ]
