# Generated by Django 5.2.6 on 2025-11-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_releavedattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='releavedemployee',
            name='ready_to_releve',
            field=models.BooleanField(default=False),
        ),
    ]
