# Generated by Django 5.2.6 on 2025-11-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_releavedemployee_ready_to_releve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='releavedemployee',
            old_name='offboarded_at',
            new_name='applied_at',
        ),
        migrations.AddField(
            model_name='releavedemployee',
            name='offboarded_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
