# Generated by Django 5.2.6 on 2025-11-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_rename_offboarded_at_releavedemployee_applied_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='absentemployeedetails',
            unique_together={('email', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('email', 'date')},
        ),
        migrations.AddIndex(
            model_name='absentemployeedetails',
            index=models.Index(fields=['email', 'date'], name='accounts_ab_email_i_199e87_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['email', 'date'], name='accounts_at_email_i_858e4f_idx'),
        ),
    ]
