# Generated by Django 5.2.6 on 2025-11-04 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_alter_absentemployeedetails_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='location_type',
            field=models.CharField(choices=[('office', 'Office')], default='office', max_length=10),
        ),
        migrations.AlterField(
            model_name='releavedattendance',
            name='location_type',
            field=models.CharField(choices=[('office', 'Office')], default='office', max_length=10),
        ),
        migrations.CreateModel(
            name='RaiseRequestAttendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('manager_remark', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'date'], name='accounts_ra_email_i_a11dda_idx'), models.Index(fields=['status'], name='accounts_ra_status_00ad38_idx')],
                'unique_together': {('email', 'date')},
            },
        ),
    ]
