# Generated by Django 5.2.6 on 2025-11-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_alter_attendance_location_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releavedattendance',
            name='location_type',
            field=models.CharField(choices=[('office', 'Office'), ('work', 'Work From Home')], default='office', max_length=10),
        ),
    ]
