# Generated by Django 5.2.6 on 2025-11-04 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_alter_releavedattendance_location_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raiserequestattendance',
            name='emp_id',
        ),
    ]
