# Generated by Django 5.2.6 on 2025-11-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_remove_raiserequestattendance_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='paid_status',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=10, null=True),
        ),
    ]
