# Generated by Django 5.2.6 on 2025-11-06 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_leave_paid_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='paid_status',
        ),
    ]
