# Generated by Django 5.2.6 on 2025-11-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_remove_leave_paid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='paid_status',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=10, null=True),
        ),
    ]