# Generated by Django 5.2.6 on 2025-11-28 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_fcmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PettyCash',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Office Supplies', 'Office Supplies'), ('Travel', 'Travel'), ('Utilities', 'Utilities'), ('Maintenance', 'Maintenance'), ('Refreshments', 'Refreshments'), ('Miscellaneous', 'Miscellaneous'), ('Monthly Fund', 'Monthly Fund'), ('Salary Advance', 'Salary Advance'), ('Emergency', 'Emergency')], max_length=50)),
                ('transaction_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pettycash_approvals', to=settings.AUTH_USER_MODEL)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Petty Cash',
                'verbose_name_plural': 'Petty Cash Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
